# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RecordService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RecordService.proto\x12\rRecordService\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"K\n\x0cMKAppRequest\x12\x0e\n\x06UserId\x18\x01 \x01(\t\x12\r\n\x05\x45mpId\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61te\x18\x03 \x01(\t\x12\x0e\n\x06Status\x18\x04 \x01(\t\":\n\x0b\x43ompleteApp\x12\x0e\n\x06UserId\x18\x01 \x01(\t\x12\r\n\x05\x45mpId\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61te\x18\x03 \x01(\t\"#\n\x10\x43ompleteAppReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rMKAppResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x08\n\x06getApp\";\n\x0bgetAppReply\x12,\n\x07message\x18\x01 \x03(\x0b\x32\x1b.RecordService.MKAppRequest2\x8d\x03\n\rRecordService\x12\x44\n\x08SayHello\x12\x1b.RecordService.HelloRequest\x1a\x19.RecordService.HelloReply\"\x00\x12I\n\rSayHelloAgain\x12\x1b.RecordService.HelloRequest\x1a\x19.RecordService.HelloReply\"\x00\x12N\n\x0fmakeAppointment\x12\x1b.RecordService.MKAppRequest\x1a\x1c.RecordService.MKAppResponse\"\x00\x12\x45\n\x0egetAppointment\x12\x15.RecordService.getApp\x1a\x1a.RecordService.getAppReply\"\x00\x12T\n\x13\x43ompleteAppointment\x12\x1a.RecordService.CompleteApp\x1a\x1f.RecordService.CompleteAppReply\"\x00\x42<\n\x1eio.grpc.examples.RecordServiceB\x12RecordServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_MKAPPREQUEST = DESCRIPTOR.message_types_by_name['MKAppRequest']
_COMPLETEAPP = DESCRIPTOR.message_types_by_name['CompleteApp']
_COMPLETEAPPREPLY = DESCRIPTOR.message_types_by_name['CompleteAppReply']
_MKAPPRESPONSE = DESCRIPTOR.message_types_by_name['MKAppResponse']
_GETAPP = DESCRIPTOR.message_types_by_name['getApp']
_GETAPPREPLY = DESCRIPTOR.message_types_by_name['getAppReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

MKAppRequest = _reflection.GeneratedProtocolMessageType('MKAppRequest', (_message.Message,), {
  'DESCRIPTOR' : _MKAPPREQUEST,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.MKAppRequest)
  })
_sym_db.RegisterMessage(MKAppRequest)

CompleteApp = _reflection.GeneratedProtocolMessageType('CompleteApp', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEAPP,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.CompleteApp)
  })
_sym_db.RegisterMessage(CompleteApp)

CompleteAppReply = _reflection.GeneratedProtocolMessageType('CompleteAppReply', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEAPPREPLY,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.CompleteAppReply)
  })
_sym_db.RegisterMessage(CompleteAppReply)

MKAppResponse = _reflection.GeneratedProtocolMessageType('MKAppResponse', (_message.Message,), {
  'DESCRIPTOR' : _MKAPPRESPONSE,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.MKAppResponse)
  })
_sym_db.RegisterMessage(MKAppResponse)

getApp = _reflection.GeneratedProtocolMessageType('getApp', (_message.Message,), {
  'DESCRIPTOR' : _GETAPP,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.getApp)
  })
_sym_db.RegisterMessage(getApp)

getAppReply = _reflection.GeneratedProtocolMessageType('getAppReply', (_message.Message,), {
  'DESCRIPTOR' : _GETAPPREPLY,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.getAppReply)
  })
_sym_db.RegisterMessage(getAppReply)

_RECORDSERVICE = DESCRIPTOR.services_by_name['RecordService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036io.grpc.examples.RecordServiceB\022RecordServiceProtoP\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=38
  _HELLOREQUEST._serialized_end=66
  _HELLOREPLY._serialized_start=68
  _HELLOREPLY._serialized_end=97
  _MKAPPREQUEST._serialized_start=99
  _MKAPPREQUEST._serialized_end=174
  _COMPLETEAPP._serialized_start=176
  _COMPLETEAPP._serialized_end=234
  _COMPLETEAPPREPLY._serialized_start=236
  _COMPLETEAPPREPLY._serialized_end=271
  _MKAPPRESPONSE._serialized_start=273
  _MKAPPRESPONSE._serialized_end=305
  _GETAPP._serialized_start=307
  _GETAPP._serialized_end=315
  _GETAPPREPLY._serialized_start=317
  _GETAPPREPLY._serialized_end=376
  _RECORDSERVICE._serialized_start=379
  _RECORDSERVICE._serialized_end=776
# @@protoc_insertion_point(module_scope)
